ALTER TABLE constituency AUTO_INCREMENT = 1;

INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Adilabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Peddapalli', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Karimnagar', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nizamabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Zahirabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Medak', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Malkajgiri', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Secunderabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hyderabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chevella', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mahabubnagar', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagarkurnool', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nalgonda', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhongir', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Warangal', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mahabubabad', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khammam', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Araku', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Srikakulam', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vizianagaram', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Visakhapatnam', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Anakapalli', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kakinada', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amalapuram', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajahmundry', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Naraspur', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Eluru', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Machilipatnam', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vijayawada', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Guntur', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Narasaraopet', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bapatla', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ongole', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nandyal', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kurnool', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Anantapur', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hindupur', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Cuddapah', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nellore', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tirupathi', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajampet', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chittoor', 500000, (select state_id from state where name like 'Andhra Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Karimganj', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Silchar', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Autonomous District', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhubri', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kokrajhar', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Barpeta', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gauhati', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mangaldoi', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tezpur', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nowgong', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kaliabor', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jorhat', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dibrugarh', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Lakhimpur', 500000, (select state_id from state where name like 'Assam'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Valmiki Nagar', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Paschim Champaran', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Purvi Champaran', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sheohar', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sitamarhi', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Madhubani', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jhanjharpur', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Supaul', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Araria', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kishanganj', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gopalganj', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Siwan', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Maharajganj', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Saran', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hajipur', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ujiarpur', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Samastipur', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Begusarai', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khagaria', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhagalpur', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Banka', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Munger', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nalanda', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Patna Sahib', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pataliputra', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arrah', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Buxar', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sasaram', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Karakat', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jahanabad', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Aurangabad', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gaya', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nawada', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jamui', 500000, (select state_id from state where name like 'Bihar'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kachchh', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Banaskantha', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Patan', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mahesana', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sabarkantha', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gandhinagar', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ahmedabad East', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ahmedabad West', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Surendranagar', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajkot', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Porbandar', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jamnagar', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Junagadh', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amreli', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhavnagar', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Anand', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kheda', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Panchmahal', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dahod', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vadodara', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chhota Udaipur', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bharuch', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bardoli', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Surat', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Navsari', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Valsad', 500000, (select state_id from state where name like 'Gujarat'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ambala', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kurukshetra', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Karnal', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sonepat', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rohtak', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Faridabad', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhiwani-Mahendragarh', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gurgaon', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hissar', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sirsa', 500000, (select state_id from state where name like 'Haryana'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mandi', 500000, (select state_id from state where name like 'Himachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shimla', 500000, (select state_id from state where name like 'Himachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kangra', 500000, (select state_id from state where name like 'Himachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hamirpur', 500000, (select state_id from state where name like 'Himachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chikkodi', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Belgaum', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bagalkot', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bijapur', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gulbarga', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raichur', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bidar', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Koppal', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bellary', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Haveri', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dharwad', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Uttara Kannada', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Davanagere', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shimoga', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Udupi Chikmagalur', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hassan', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dakshina Kannada', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chitradurga', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tumkur', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mandya', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mysore', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chamarajanagar', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bangalore Rural', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bangalore North', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bangalore Central', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bangalore South', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chikballapur', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kolar', 500000, (select state_id from state where name like 'Karnataka'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kasaragod', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kannur', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vadakara', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Wayanad', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kozhikode', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Malappuram', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ponnani', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Palakkad', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Alathur', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thrissur', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chalakudy', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ernakulam', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Idukki', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kottayam', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Alappuzha', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mavelikara', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pathanamthitta', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kollam', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Attingal', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thiruvananthapuram', 500000, (select state_id from state where name like 'Kerala'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Morena', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhind', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gwalior', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Guna', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sagar', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tikamgarh', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Damoh', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khajuraho', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Satna', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rewa', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sidhi', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shahdol', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jabalpur', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mandla', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Balaghat', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chhindwara', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hoshangabad', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vidisha', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhopal', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajgarh', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dewas', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ujjain', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mandsaur', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ratlam', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhar', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Indore', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khargone', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khandwa', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Betul', 500000, (select state_id from state where name like 'Madhya Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nandurbar', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhule', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalgaon', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raver', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Buldhana', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Akola', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amravati', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Wardha', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ramtek', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagpur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhandara-Gondiya', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gadchiroli-Chimur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chandrapur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Yavatmal-Washim', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hingoli', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nanded', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Parbhani', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalna', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Aurangabad', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dindori', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nashik', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Palghar', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhiwandi', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kalyan', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thane', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai North', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai North West', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai North East', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai North Central', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai South Central', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mumbai South', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raigad', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Maval', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pune', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Baramati', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shirur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ahmednagar', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shirdi', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Beed', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Osmanabad', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Latur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Solapur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Madha', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sangli', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Satara', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ratnagiri–Sindhudurg', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kolhapur', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ichalkaranji', 500000, (select state_id from state where name like 'Maharashtra'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Inner Manipur', 500000, (select state_id from state where name like 'Manipur'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Outer Manipur', 500000, (select state_id from state where name like 'Manipur'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bargarh', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sundargarh', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sambalpur', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Keonjhar', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mayurbhanj', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Balasore', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhadrak', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jajpur', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhenkanal', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bolangir', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kalahandi', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nabarangpur', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kandhamal', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Cuttack', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kendrapara', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jagatsinghpur', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Puri', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhubaneswar', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Aska', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Berhampur', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Koraput', 500000, (select state_id from state where name like 'Odisha'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gurdaspur', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amritsar', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khadoor Sahib', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalandhar', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hoshiarpur', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Anandpur Sahib', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ludhiana', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Fatehgarh Sahib', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Faridkot', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Firozpur', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bathinda', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sangrur', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Patiala', 500000, (select state_id from state where name like 'Punjab'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thiruvallur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chennai North', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chennai South', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chennai Central', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sriperumbudur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kancheepuram', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arakkonam', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Vellore', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Krishnagiri', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dharmapuri', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tiruvannamalai', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arani', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Villupuram', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kallakurichi', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Salem', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Namakkal', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Erode', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tiruppur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nilgiris', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Coimbatore', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pollachi', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dindigul', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Karur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tiruchirappalli', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Perambalur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Cuddalore', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chidambaram', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mayiladuturai', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagapattinam', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thanjavur', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sivaganga', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Madurai', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Theni', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Virudhunagar', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ramanathapuram', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Thoothukudi', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tenkasi', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tirunelveli', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kanyakumari', 500000, (select state_id from state where name like 'Tamil Nadu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Saharanpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kairana', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Muzaffarnagar', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bijnor', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagina', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Moradabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rampur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sambhal', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amroha', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Meerut', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Baghpat', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ghaziabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gautam Buddha Nagar', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bulandshahr', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Aligarh', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hathras', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mathura', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Agra', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Fatehpur Sikri', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Firozabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mainpuri', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Etah', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Badaun', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Aonla', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bareilly', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pilibhit', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shahjahanpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kheri', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhaurahra', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sitapur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hardoi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Misrikh', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Unnao', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mohanlalganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Lucknow', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rae Bareli', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Amethi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sultanpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pratapgarh', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Farrukhabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Etawah', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kannauj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kanpur Urban', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kanpur Rural', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalaun', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jhansi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hamirpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Banda', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Fatehpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kaushambi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Phulpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Allahabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Barabanki', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Faizabad', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ambedkar Nagar', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bahraich', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kaiserganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shrawasti', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gonda', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Domariyaganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Basti', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sant Kabir Nagar', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Maharajganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Gorakhpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kushi Nagar', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Deoria', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bansgaon', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Lalganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Azamgarh', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ghosi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Salempur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ballia', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jaunpur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Machhlishahr', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ghazipur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chandauli', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Varanasi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhadohi', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mirzapur', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Robertsganj', 500000, (select state_id from state where name like 'Uttar Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Cooch Behar', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Alipurduars', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalpaiguri', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Darjeeling', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raiganj', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Balurghat', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Maldaha Uttar', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Maldaha Dakshin', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jangipur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Baharampur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Murshidabad', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Krishnanagar', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ranaghat', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bangaon', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Barrackpur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dum Dum', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Barasat', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Basirhat', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jaynagar', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mathurapur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Diamond Harbour', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jadavpur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kolkata Dakshin', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kolkata Uttar', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Howrah', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Uluberia', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sreerampur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hooghly', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arambag', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tamluk', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kanthi', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ghatal', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jhargram', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Medinipur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Purulia', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bankura', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bishnupur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bardhaman Purba', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bardhaman-Durgapur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Asansol', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bolpur', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Birbhum', 500000, (select state_id from state where name like 'West Bengal'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chandni Chowk', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('North East Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('East Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('New Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('North West Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('West Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('South Delhi', 500000, (select state_id from state where name like 'Delhi'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arunachal West', 500000, (select state_id from state where name like 'Arunachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Arunachal East', 500000, (select state_id from state where name like 'Arunachal Pradesh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bastar', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bilaspur', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Durg', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Janjagir', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kanker', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Korba', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raigarh', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Raipur', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajnandgaon', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sarguja', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mahasamund', 500000, (select state_id from state where name like 'Chhattisgarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('North Goa', 500000, (select state_id from state where name like 'Goa'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('South Goa', 500000, (select state_id from state where name like 'Goa'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Baramulla', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Srinagar', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Anantnag', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ladakh', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Udhampur', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jammu', 500000, (select state_id from state where name like 'Jammu and Kashmir'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Rajmahal', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dumka', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Godda', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chatra', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kodarma', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Giridih', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dhanbad', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ranchi', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jamshedpur', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Singhbhum', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Khunti', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Lohardaga', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Palamau', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Hazaribagh', 500000, (select state_id from state where name like 'Jharkhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Shillong', 500000, (select state_id from state where name like 'Meghalaya'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tura', 500000, (select state_id from state where name like 'Meghalaya'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Mizoram', 500000, (select state_id from state where name like 'Mizoram'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagaland', 500000, (select state_id from state where name like 'Nagaland'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ganganagar', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bikaner', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Churu', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jhunjhunu', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sikar', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jaipur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dausa', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Alwar', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bharatpur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bayana', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sawai Madhopur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Ajmer', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tonk', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Kota', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jhalawar', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Banswara', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Salumber', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Udaipur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chittorgarh', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Bhilwara', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Pali', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jalore', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Barmer', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Jodhpur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nagaur', 500000, (select state_id from state where name like 'Rajasthan'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Sikkim', 500000, (select state_id from state where name like 'Sikkim'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tripura West', 500000, (select state_id from state where name like 'Tripura'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tripura East', 500000, (select state_id from state where name like 'Tripura'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Tehri Garhwal', 500000, (select state_id from state where name like 'Uttarakhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Garhwal', 500000, (select state_id from state where name like 'Uttarakhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Almora', 500000, (select state_id from state where name like 'Uttarakhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Nainital', 500000, (select state_id from state where name like 'Uttarakhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Haridwar', 500000, (select state_id from state where name like 'Uttarakhand'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Andaman and Nicobar Islands', 500000, (select state_id from state where name like 'Andaman and Nicobar Islands'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Chandigarh', 500000, (select state_id from state where name like 'Chandigarh'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Dadra and Nagar Haveli', 500000, (select state_id from state where name like 'Dadra and Nagar Haveli'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Daman and Diu', 500000, (select state_id from state where name like 'Daman and Diu'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Lakshadweep', 500000, (select state_id from state where name like 'Lakshdweep'), 1);
INSERT INTO constituency ( name, population, stateId, parliament) VALUES('Puducherry', 500000, (select state_id from state where name like 'Puducherry'), 1);
