ALTER TABLE state AUTO_INCREMENT = 1;
INSERT INTO state( name, ut) VALUES ('Andhra Pradesh',0);
INSERT INTO state( name, ut) VALUES ('Arunachal Pradesh',0);
INSERT INTO state( name, ut) VALUES ('Assam',0);
INSERT INTO state( name, ut) VALUES ('Bihar',0);
INSERT INTO state( name, ut) VALUES ('Chhattisgarh',0);
INSERT INTO state( name, ut) VALUES ('Goa',0);
INSERT INTO state( name, ut) VALUES ('Gujarat',0);
INSERT INTO state( name, ut) VALUES ('Haryana',0);
INSERT INTO state( name, ut) VALUES ('Himachal Pradesh',0);
INSERT INTO state( name, ut) VALUES ('Jammu and Kashmir',0);
INSERT INTO state( name, ut) VALUES ('Jharkhand',0);
INSERT INTO state( name, ut) VALUES ('Karnataka',0);
INSERT INTO state( name, ut) VALUES ('Kerala',0);
INSERT INTO state( name, ut) VALUES ('Maharashtra',0);
INSERT INTO state( name, ut) VALUES ('Manipur',0);
INSERT INTO state( name, ut) VALUES ('Meghalaya',0);
INSERT INTO state( name, ut) VALUES ('Mizoram',0);
INSERT INTO state( name, ut) VALUES ('Nagaland',0);
INSERT INTO state( name, ut) VALUES ('Odisha',0);
INSERT INTO state( name, ut) VALUES ('Punjab',0);
INSERT INTO state( name, ut) VALUES ('Sikkim',0);
INSERT INTO state( name, ut) VALUES ('Tamil Nadu',0);
INSERT INTO state( name, ut) VALUES ('Tripura',0);
INSERT INTO state( name, ut) VALUES ('Uttarakhand',0);
INSERT INTO state( name, ut) VALUES ('Uttar Pradesh',0);
INSERT INTO state( name, ut) VALUES ('West Bengal',0);
INSERT INTO state( name, ut) VALUES ('Rajasthan',0);
INSERT INTO state( name, ut) VALUES ('Madhya Pradesh',0);
